#!/usr/bin/env tsx
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const rootDir = resolve(__dirname, "..");
const changelogPath = resolve(rootDir, "docs/CHANGELOG.md");
const outputPath = resolve(rootDir, "packages/ui/client/src/changelogData.ts");

export interface ChangelogRelease {
  version: string;
  date?: string;
  title: string;
  content: string;
}

export function parseChangelog(markdown: string): ChangelogRelease[] {
  const lines = markdown.split(/\r?\n/);
  const releases: ChangelogRelease[] = [];

  let currentRelease: ChangelogRelease | null = null;
  const currentLines: string[] = [];

  const flush = () => {
    if (currentRelease) {
      currentRelease.content = currentLines.join("\n").trim();
      releases.push(currentRelease);
      currentLines.length = 0;
    }
  };

  for (const line of lines) {
    const headerMatch = line.match(/^##\s+v?(\d+\.\d+\.\d+(?:-[\w.]+)?)(?:\s+[—–-]\s+(\d{4}-\d{2}-\d{2}))?(.*)$/);

    if (headerMatch) {
      flush();
      const version = headerMatch[1]!;
      const date = headerMatch[2];
      const extra = (headerMatch[3] || "").trim();
      currentRelease = {
        version,
        ...(date ? { date } : {}),
        title: `v${version}${date ? ` (${date})` : ""}${extra ? ` ${extra}` : ""}`,
        content: "",
      };
    } else if (line.startsWith("## Archived") || line.startsWith("---")) {
      if (line.startsWith("## Archived")) {
        flush();
        currentRelease = null;
        break;
      }
      if (currentRelease) {
        currentLines.push(line);
      }
    } else if (currentRelease) {
      currentLines.push(line);
    }
  }

  flush();
  return releases;
}

function main() {
  const markdown = readFileSync(changelogPath, "utf-8");
  const releases = parseChangelog(markdown);

  if (releases.length === 0) {
    throw new Error(`Failed to parse any releases from ${changelogPath}`);
  }

  const fileContent = `// Auto-generated by scripts/sync-changelog.ts from docs/CHANGELOG.md.
// Do not edit directly; update docs/CHANGELOG.md and run \`pnpm sync:changelog\`.

export interface ChangelogRelease {
  version: string;
  date?: string;
  title: string;
  content: string;
}

export const CHANGELOG_RELEASES: readonly ChangelogRelease[] = ${JSON.stringify(releases, null, 2)} as const;
`;

  writeFileSync(outputPath, fileContent, "utf-8");
  console.log(`Synced ${releases.length} releases to ${outputPath} (latest: v${releases[0]?.version})`);
}

if (process.argv[1] === __filename) {
  main();
}
